/**
 * Shared API contract types. Imported by both the UI and the route handlers.
 * See PRD §6.
 */

/**
 * What the user can pick in the file dialog. Background removal happens in
 * the browser, so the actual POST body is always a `image/png` (see
 * UPLOAD_MIME_TYPE) — these mimes are only for the `<input accept>` filter.
 */
export const ACCEPTED_MIME_TYPES = [
  "image/png",
  "image/jpeg",
  "image/webp",
] as const satisfies readonly string[];
export type AcceptedMimeType = (typeof ACCEPTED_MIME_TYPES)[number];

/**
 * The mime the server accepts on POST /api/images. The browser bg-removal
 * pipeline always produces a PNG, so anything else is a misconfigured client.
 */
export const UPLOAD_MIME_TYPE = "image/png" as const;

/**
 * Hard upload limit shared by the client (pre-flight) and the API route.
 * The actual bytes go directly to R2 via a presigned PUT URL, so this is
 * NOT bounded by Vercel's 4.5 MB function-body limit.
 */
export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

/**
 * Max edge (in CSS pixels) the client downscales the input to before running
 * bg-removal. Keeps WASM inference fast and the final PNG small enough to
 * upload over typical home connections in a few seconds.
 */
export const CLIENT_MAX_EDGE_PX = 1024;

/**
 * Image id format. Generated by `nanoid` (URL-safe alphabet); routes use
 * this to reject clearly-bogus paths before hitting storage.
 */
export const IMAGE_ID_RE = /^[A-Za-z0-9_-]{6,32}$/;


export type ApiResponse<T> =
  | { ok: true; data: T }
  | { ok: false; error: { code: ErrorCode; message: string } };

export const ErrorCodes = {
  INVALID_FILE: "INVALID_FILE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  BG_REMOVAL_FAILED: "BG_REMOVAL_FAILED",
  STORAGE_FAILED: "STORAGE_FAILED",
  NOT_FOUND: "NOT_FOUND",
  EXPIRED: "EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ImageDTO {
  id: string;
  shareUrl: string;
  previewUrl: string;
  filename: string;
  /** ISO timestamp */
  createdAt: string;
  /** ISO timestamp */
  expiresAt: string;
  bytes: number;
  mime: string;
}

/**
 * Returned by `POST /api/images`. The client uses `uploadUrl` + `headers` to
 * PUT the bytes directly to R2, then navigates to `image.shareUrl`. The
 * server-side route never touches the bytes — it only mints the presigned URL.
 */
export interface SignedUploadDTO {
  image: ImageDTO;
  upload: {
    url: string;
    method: "PUT";
    headers: Record<string, string>;
    expiresInSeconds: number;
  };
}
